name: Build dfu-programmer

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Dependencies
        run: |
          C:/msys64/usr/bin/pacman --noconfirm -S automake-wrapper autoconf-wrapper make mingw-w64-x86_64-libusb-compat-git

          echo "Ignore the 'error: command (/usr/bin/sh ...'  above"

          # mingw-w64-x86_64-gcc

          # choco install pkgconfiglite

          # dir C:\ProgramData\chocolatey\lib\pkgconfiglite
          # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools
          # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*
          # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*\*

          # mv C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*\share\aclocal C:\MSYS64\mingw64\share\

      - uses: actions/checkout@v3

      - name: bootstrap
        shell: C:/msys64/usr/bin/mintty.exe --hold never --log - --exec {0}
        run: |
          echo Path is: $PATH
          export PATH=$(node -e "console.log('$(echo $PATH)'.replace('/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin','/c/msys64/usr/bin'))")
          echo Path is: $PATH
          ./bootstrap.sh 2>&1

      - name: Check configure exists
        shell: bash
        run: ls -l configure

      - name: configure
        shell: C:/msys64/usr/bin/mintty.exe --hold never --log - --exec {0}
        run: ./configure --disable-dependency-tracking --disable-libusb_1_0

      - name: Check makefile exists
        shell: bash
        run: ls -l Makefile

      - name: make
        shell: C:/msys64/usr/bin/mintty.exe --hold never --log - --exec {0}
        run: make

      - run: src/dfu-programmer.exe --help

      - name: Upload dfu-programmer.exe
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer.exe binary for Windows x64
          path: src/dfu-programmer.exe

      - name: make dist
        shell: C:/msys64/usr/bin/mintty.exe --hold never --log - --exec {0}
        run: make dist

      - name: Upload .zip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for Windows
          path: '*.zip'

  Linux:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install -y libusb-dev

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for Linux x64
          path: src/dfu-programmer

  macOS:
    runs-on: macos-latest

    steps:
      - run: brew install automake

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for macOS Universal
          path: src/dfu-programmer
