name: Build dfu-programmer

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies, bootstrap, configure, and make
        shell: C:/msys64/usr/bin/bash.exe --noprofile --norc -e -x -o pipefail {0}
        run: |
          export PATH=/usr/bin:/mingw64/bin:/usr/local/bin

          pacman --noconfirm -S automake-wrapper autoconf-wrapper make mingw-w64-i686-gcc

          ./bootstrap.sh 2>&1

          find /mingw64 -type f -name libusb.a

          cp windows/usb.h /mingw64/include/
          cp windows/libusb.a /mingw64/lib/

          ./configure --disable-dependency-tracking --disable-libusb_1_0
          gcc -xc -E -v /dev/null

          make

          ls -lR

      - run: echo $PATH

      - name: Upload dfu-programmer.exe
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer.exe binary for Windows x64
          path: src/dfu-programmer.exe

      - name: make dist
        shell: C:/msys64/usr/bin/bash.exe --noprofile --norc -e -o pipefail {0}
        run: |
          export PATH=/usr/bin:/mingw64/bin:/usr/local/bin
          make dist

      - name: Upload .zip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for Windows
          path: "*.zip"

      - name: Run with bash
        shell: C:/msys64/usr/bin/bash.exe --noprofile --norc -e -o pipefail {0}
        run: |
          export PATH=/usr/bin:/mingw64/bin:/usr/local/bin
          src/dfu-programmer.exe --help

  Linux:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install -y libusb-dev

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for Linux x64
          path: src/dfu-programmer

      - name: make dist
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for Linux
          path: "*.tar.gz"

  macOS:
    runs-on: macos-latest

    steps:
      - run: brew install automake

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for macOS Universal
          path: src/dfu-programmer

      - name: make dist
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for macOS
          path: "*.tar.gz"
