name: Build dfu-programmer

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Dependencies
        run: |
          C:/msys64/usr/bin/pacman --noconfirm -S automake-wrapper autoconf-wrapper make mingw-w64-x86_64-libusb-compat-git mingw-w64-x86_64-libusb mingw-w64-x86_64-gcc

          echo "Ignore the 'error: command (/usr/bin/sh ...'  above"

        # mingw-w64-x86_64-gcc

        # choco install pkgconfiglite

        # dir C:\ProgramData\chocolatey\lib\pkgconfiglite
        # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools
        # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*
        # dir C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*\*

        # mv C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\*\share\aclocal C:\MSYS64\mingw64\share\

      - uses: actions/checkout@v3

      - name: Bootstrap, configure, and make
        shell: C:/msys64/usr/bin/bash.exe --noprofile --norc -e -x -o pipefail {0}
        run: |
          export PATH=/usr/bin:/mingw64/bin:/usr/local/bin
          ./bootstrap.sh 2>&1

          rm /mingw64/include/usb.h
          ln -snf /mingw64/include/libusb-compat/usb.h /mingw64/include/

          ./configure --disable-dependency-tracking --disable-libusb_1_0
          gcc -xc -E -v /dev/null

          make

      - run: src/dfu-programmer.exe --help

      - name: Upload dfu-programmer.exe
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer.exe binary for Windows x64
          path: src/dfu-programmer.exe

      - name: make dist
        shell: C:/msys64/usr/bin/bash.exe --noprofile --norc -e -o pipefail {0}
        run: |
          export PATH=$(node -e "console.log('$(echo $PATH)'.replace('/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin','/c/msys64/usr/bin'))")
          make dist

      - name: Upload .zip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for Windows
          path: "*.zip"

  Linux:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install -y libusb-dev

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for Linux x64
          path: src/dfu-programmer

      - name: make dist
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for Linux
          path: "*.tar.gz"

  macOS:
    runs-on: macos-latest

    steps:
      - run: brew install automake

      - uses: actions/checkout@v3

      - name: bootstrap
        run: ./bootstrap.sh

      - name: configure
        run: ./configure

      - name: make
        run: make

      - run: src/dfu-programmer --help

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer binary for macOS Universal
          path: src/dfu-programmer

      - name: make dist
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dfu-programmer for macOS
          path: "*.tar.gz"
